### PR TITLE
Reformatted Changes file as per CPAN::Changes::Spec

### PR DESCRIPTION
**Pull request by neilb**
Hi,

I've reformatted your Changes file according to the spec in CPAN::Changes::Spec. It only required minor tweaks.

Following this format means that various tools can more easily process your distribution automatically.

You can find out more about this at Brian Cassidy's [CPAN::Changes Kwalitee Service](http://changes.cpanhq.org), which is where I saw your module listed :-)

Cheers,
Neil

PS I'm doing this because I'm on a quest to help improve CPAN:

> http://questhub.io/realm/perl/quest/51f0337718ba7d3959000086

### CODE REVIEW

**Comment by rehsack** [comment]
tidy_changelog produced my one. Can you explain how you're changes imrpove when CPAN::Changes produces and ok() the Changes as distributed?

**Comment by neilb** [comment]
Hmm, that's odd, and I can appreciate it might be a pain to have me come along and fiddle with it when another tool has already said it's good.

Here's the report from Brian Cassidy's online check:

> http://changes.cpanhq.org/dist/Alien-Packages/0.003

So the specific thing was the dash (-) before the date on one of the releases.

**Comment by rehsack** [comment]
Well, can you give me the tidy_changelog command line options you're using? Or do you do that by hand?

**Comment by neilb** [comment]
By hand.

**Comment by rehsack** [comment]
That explains a lot ;)

I'd like (to avoid issues with CPAN::Changes) to see future pull requests using tidy_changelog.
For now, I'll add an extra author tests and populate it into all other repo's I maintain.

**Pull request merged**
